### ISSUE TITLE
Dataset is not available

### ISSUE THREAD

**Issue by NellyElsayed** [MIMBCD-UI/dataset-uta7-time#1]
Hello. I am trying to access your dataset on Kaggle, however, the link does not work and Kaggle shows the message "We can't find that page." Please advise how I can get access to your dataset.

**Comment by FMCalisto** [comment]
Thank you for reaching out. Unfortunately, the [Kaggle organizations functionality was suspended](https://www.kaggle.com/discussions/getting-started/209272). Because of that, you can't access anymore the available dataset. However, you have the dataset here on GitHub as well.

Please refer to the following links:

https://github.com/MIMBCD-UI/dataset-uta7-time/tree/master/dataset

https://github.com/MIMBCD-UI/dataset-uta7-time?tab=readme-ov-file#related-repositories
